// Live driver. The widget invokes our factory (via register) with the container,
// the bridge, and the per-session ctx (seed / config / skin / locale). We boot the
// Bevy render build (WebGL2) into a canvas, hand it the seed + resolved config, and
// listen for the `wallsmash:finish` event Bevy dispatches with the recorded trace.
// On a win we submit that trace through `bridge.pass({ trace })`; the server replays
// it under the same seed to compute the authoritative verdict.

import type { Bridge, GameContext, Seed } from '@caputchin/game-sdk';
import { configToInts } from './config.js';
import { applyStyles, createBootOverlay } from './styles.js';
import { createSfx } from './audio.js';
import { createAnnouncer } from './a11y.js';
import { buildStrings, localeVec } from './strings.js';
import liveWasmB64 from './generated/live-wasm.js';
// wasm-bindgen `--target web` glue (generated by build:wasm, bundled into the
// IIFE). Kept in build/ outside src/; the bundler resolves it at build time.
// @ts-expect-error -- generated module, no published types
import init, { start } from '../build/bindgen/wall_smash.js';

interface FinishDetail {
  passed: boolean;
  trace: Uint8Array;
}

function decodeBase64(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
  return out;
}

function encodeBase64(bytes: Uint8Array): string {
  let bin = '';
  for (let i = 0; i < bytes.length; i += 1) bin += String.fromCharCode(bytes[i] ?? 0);
  return btoa(bin);
}

// Detect a software / downlevel WebGL2 renderer (SwiftShader, llvmpipe, ...). Bevy's
// real 3D (PBR) shaders fail there, so the modern skin falls back to the 2D look.
// A blocked WEBGL_debug_renderer_info (privacy mode) -> assume hardware, try 3D.
function isSoftwareGL(): boolean {
  try {
    const gl = document.createElement('canvas').getContext('webgl2');
    if (!gl) return true; // no WebGL2 at all -> use 2D
    const ext = gl.getExtension('WEBGL_debug_renderer_info');
    if (!ext) return false;
    const r = String(gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)).toLowerCase();
    return (
      r.includes('swiftshader') ||
      r.includes('llvmpipe') ||
      r.includes('software') ||
      r.includes('basic render')
    );
  } catch {
    return false;
  }
}

// TEST-ONLY escape hatch for visual verification. A same-window dev mount (the
// render-check page) may set `globalThis.__CAPUTCHIN_FORCE_3D = true` to force the
// real 3D path even on a software WebGL2 backend (SwiftShader, llvmpipe), so an
// automated browser with no GPU can still screenshot the 3D scene. Inert in
// production by construction: the live game runs inside a sandboxed cross-origin
// iframe, where `window.top !== window.self` and the parent global is unreachable,
// so this returns false for every real visitor.
function forceReal3d(): boolean {
  try {
    return (
      typeof window !== 'undefined' &&
      window.top === window.self &&
      (globalThis as { __CAPUTCHIN_FORCE_3D?: unknown }).__CAPUTCHIN_FORCE_3D === true
    );
  } catch {
    return false;
  }
}

// Parse a skin color (#rgb / #rrggbb) into a packed 0xRRGGBB int for the Bevy build.
function hexToU32(v: unknown): number | null {
  if (typeof v !== 'string') return null;
  let h = v.trim().replace('#', '');
  if (h.length === 3) {
    h = h
      .split('')
      .map((ch) => ch + ch)
      .join('');
  }
  if (h.length !== 6 || /[^0-9a-fA-F]/.test(h)) return null;
  return parseInt(h, 16);
}

// Sentinel for a skin key the customer left unset: the Bevy build keeps that key's
// baked default (and, for `brick`, the multi-color ARCADE wall). Distinct from any
// valid 0xRRGGBB color (which is <= 0xffffff).
const PALETTE_UNSET = 0xffffffff;

// Build the [background, brick, ball, paddle, accent] palette ints from ctx.skin.
// Each key is independently overridable; a missing/invalid key becomes PALETTE_UNSET
// so the Bevy build falls back per-key rather than wholesale. Returns [] if no skin.
function paletteFromSkin(skin: GameContext['skin']): number[] {
  if (!skin) return [];
  const keys = ['background', 'brick', 'ball', 'paddle', 'accent'];
  return keys.map((k) => hexToU32(skin[k]) ?? PALETTE_UNSET);
}

// A play seed for unverified sessions (no server seed). Host-side randomness only;
// the deterministic sim never touches it directly (it receives this fixed seed).
function fallbackSeed(): Seed {
  const a = new Uint32Array(4);
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) crypto.getRandomValues(a);
  else for (let i = 0; i < 4; i += 1) a[i] = (i + 1) * 0x9e3779b1;
  return [a[0] ?? 1, a[1] ?? 2, a[2] ?? 3, a[3] ?? 4] as Seed;
}

export interface GameOptions {
  container: HTMLElement;
  bridge: Bridge;
  ctx?: GameContext;
}

export function runWallSmash(opts: GameOptions): () => void {
  const { container, bridge, ctx } = opts;

  const canvas = document.createElement('canvas');
  canvas.id = 'wallsmash';
  applyStyles(container, canvas);
  container.appendChild(canvas);

  // Boot loader: shown until Bevy paints its first frame (fires `wallsmash:ready`).
  const boot = createBootOverlay(container.ownerDocument);
  container.appendChild(boot);
  const onReady = () => boot.remove();
  window.addEventListener('wallsmash:ready', onReady, { once: true });

  // Screen-reader bridge: the Bevy canvas is opaque to assistive tech, so a hidden
  // aria-live region speaks the game state. Localized via strings.ts; fed by the
  // `wallsmash:announce` events Bevy emits. Visuals stay 100% in Bevy.
  const strings = buildStrings(ctx?.locale ?? null);
  const announcer = createAnnouncer(container.ownerDocument);
  container.setAttribute('role', 'group');
  container.setAttribute('aria-label', strings.t('ariaGame'));
  container.setAttribute('lang', strings.lang);
  if (strings.direction === 'rtl') container.setAttribute('dir', 'rtl');
  container.appendChild(announcer.element);
  const onAnnounce = (e: Event) => {
    const d = (e as CustomEvent<{ kind: string; n: number }>).detail;
    if (!d) return;
    switch (d.kind) {
      case 'launch':
        announcer.say(strings.t('announceLaunch'));
        break;
      case 'level':
        announcer.say(strings.t('announceLevel', { level: d.n }));
        break;
      case 'lifeLost':
        announcer.say(strings.t('announceLifeLost', { lives: d.n }));
        break;
      case 'verified':
        announcer.say(strings.t('announceVerified'));
        break;
      case 'roundOver':
        announcer.say(strings.t('announceLose'));
        break;
    }
  };
  window.addEventListener('wallsmash:announce', onAnnounce);

  const seed = ctx?.seed ?? fallbackSeed();
  const cfgInts = Array.from(configToInts(ctx?.config ?? null));
  // The look (2D retro vs 3D modern) is a SKIN field (`style`: "2d" | "3d"), a
  // presentational axis the widget/host can set, theme-independent. It never touches
  // the deterministic sim, so it can't affect replay. Render modes: 0 = retro 2D;
  // 1 = modern 2D fallback (software GL); 2 = modern real 3D (GPU). The software-GL
  // downgrade is skipped when the test-only force flag is set (forceReal3d), so a
  // GPU-less automated browser can still render the real 3D scene.
  const want3d = ctx?.skin?.['style'] === '3d';
  const mode = want3d ? (isSoftwareGL() && !forceReal3d() ? 1 : 2) : 0;
  const palette = paletteFromSkin(ctx?.skin ?? null);

  const soundOn = ctx?.config?.['sound'] !== false; // default on; customer can disable
  const sfx = createSfx(!soundOn); // the in-canvas speaker button toggles it at runtime

  let submitted = false;
  const onFinish = (e: Event) => {
    const detail = (e as CustomEvent<FinishDetail>).detail;
    if (!detail || submitted) return;
    if (detail.passed && detail.trace && detail.trace.length > 0) {
      submitted = true;
      bridge.pass({ trace: encodeBase64(detail.trace) });
    }
    // A lost round is silent: per the SDK, no failure signal -> the visitor simply
    // does not pass. The in-iframe UI handles retry messaging.
  };
  const onSfx = (e: Event) => {
    const name = (e as CustomEvent<{ name: string }>).detail?.name;
    if (name) sfx.play(name);
  };
  // The in-canvas Bevy speaker button toggles sound; (un)mute the WebAudio sfx.
  const onSound = (e: Event) => {
    const on = (e as CustomEvent<{ on: boolean }>).detail?.on;
    if (typeof on === 'boolean') sfx.setMuted(!on);
  };
  // Audio needs a user gesture; the player's first interaction unlocks it.
  const onGesture = () => sfx.resume();
  window.addEventListener('wallsmash:finish', onFinish);
  window.addEventListener('wallsmash:sfx', onSfx);
  window.addEventListener('wallsmash:sound', onSound);
  container.addEventListener('pointerdown', onGesture);
  window.addEventListener('keydown', onGesture);

  // Boot Bevy: instantiate from the inlined bytes (CSP connect-src 'none' forbids a
  // fetch), then hand the sim its seed + config. Runtime byte-instantiation is
  // allowed in the live iframe (only the replay isolate forbids it).
  let cancelled = false;
  init({ module_or_path: decodeBase64(liveWasmB64) })
    .then(() => {
      if (cancelled) return;
      // Pass the initial muted state so the Bevy speaker icon matches the audio from
      // the first frame (the in-canvas button toggles both thereafter).
      start(
        [seed[0], seed[1], seed[2], seed[3]],
        cfgInts,
        mode,
        palette,
        localeVec(ctx?.locale ?? null),
        !soundOn,
      );
    })
    .catch((err: unknown) => {
      bridge.error({ code: 'engine-init-failed', message: String(err) });
    });

  return () => {
    cancelled = true;
    window.removeEventListener('wallsmash:finish', onFinish);
    window.removeEventListener('wallsmash:sfx', onSfx);
    window.removeEventListener('wallsmash:sound', onSound);
    window.removeEventListener('wallsmash:ready', onReady);
    window.removeEventListener('wallsmash:announce', onAnnounce);
    container.removeEventListener('pointerdown', onGesture);
    window.removeEventListener('keydown', onGesture);
    sfx.dispose();
    boot.remove();
    announcer.element.remove();
    canvas.remove();
  };
}
