// Ambient declarations for the WASM modules the bundler/loader resolve, so `tsc`
// type-checks without the built artifacts present.

// Resolved by the replay isolate's module map (precompiled), kept external by tsup.
declare module './wall-smash.wasm' {
  const mod: WebAssembly.Module;
  export default mod;
}

// NOTE: the base64 live-render wasm (./generated/live-wasm.js) is typed by the
// committed src/generated/live-wasm.d.ts, not an ambient declaration here. Under
// moduleResolution "bundler" a relative-path `declare module` is NOT honored for
// resolution, so tsc needs a real declaration file at the resolved path. That
// committed stub lets typecheck run without the heavy live build; `build` emits
// the live-wasm.ts value alongside it (tsc prefers the .ts when both exist).

// Generated by build:wasm (wasm-bindgen `--target web` glue for the live build);
// kept in build/ (excluded from tsc), resolved by the bundler into the live IIFE.
declare module '../build/bindgen/wall_smash.js' {
  export default function init(opts?: {
    module_or_path: BufferSource | WebAssembly.Module;
  }): Promise<unknown>;
  export function start(
    seed: number[],
    cfg: number[],
    style: number,
    palette: number[],
    locale: string[],
    muted: boolean,
  ): void;
}
