// Ambient declarations for the WASM modules the bundler/loader resolve, so `tsc`
// type-checks without the built artifacts present.

// Resolved by the replay isolate's module map (precompiled), kept external by tsup.
declare module './wall-smash.wasm' {
  const mod: WebAssembly.Module;
  export default mod;
}

// Generated by build:wasm (base64 of the optimized live render wasm); resolved by
// the bundler into the live IIFE.
declare module './generated/live-wasm.js' {
  const wasmB64: string;
  export default wasmB64;
}

// Generated by build:wasm (wasm-bindgen `--target web` glue for the live build);
// kept in build/ (excluded from tsc), resolved by the bundler into the live IIFE.
declare module '../build/bindgen/wall_smash.js' {
  export default function init(opts?: {
    module_or_path: BufferSource | WebAssembly.Module;
  }): Promise<unknown>;
  export function start(seed: number[], cfg: number[], style: number, palette: number[]): void;
}
