// Inline the CC0 ingredient PNGs (src/art/sprites/*.png) into a TS module of
// base64 data-URIs, so the live bundle carries the art with no runtime fetch
// (the widget CSP forbids network) and no bundler asset-loader config.
//
// Re-run after changing the sprite set:  node scripts/gen-sprites.mjs
// The art is Glitch (Tiny Speck), CC0 / public domain - see src/art/CREDITS.md.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const spriteDir = join(here, '..', 'src', 'art', 'sprites');
const out = join(here, '..', 'src', 'art', 'sprites.generated.ts');

const names = readdirSync(spriteDir)
  .filter((f) => f.endsWith('.png'))
  .sort();

const entries = names.map((file) => {
  const key = file.replace(/\.png$/, '');
  const b64 = readFileSync(join(spriteDir, file)).toString('base64');
  return `  ${key}: 'data:image/png;base64,${b64}',`;
});

const body = `// AUTO-GENERATED by scripts/gen-sprites.mjs - do not edit by hand.
// Glitch (Tiny Speck) food art, CC0 / public domain. See src/art/CREDITS.md.
// Each value is a self-contained PNG data-URI (no runtime fetch).

/** Ingredient sprite atlas: ingredient key -> PNG data-URI. */
export const SPRITES: Record<string, string> = {
${entries.join('\n')}
};
`;

writeFileSync(out, body);
console.log(`wrote ${out} with ${names.length} sprites`);
