// Live Phobos driver: mounts the real DOOM engine to a canvas inside the game
// iframe, records the player's input as the opaque trace, and releases the
// captcha via bridge.pass({ trace }) once the seeded kill goal is met. The
// server replays the same trace over the same seed (src/run.ts) to verify.
// @ts-expect-error -- generated Emscripten glue
import createPhobosLive from '../build/phobos-live.js';
// Generated by build:engines -- the live wasm (engine + WAD) as one base64 string.
import liveWasmB64 from './generated/phobos-live-wasm.js';
import { STAGE_WIDTH, STAGE_HEIGHT, mountStyles } from './styles.js';
import { DOOM_KEYS, mapKey } from './input.js';
import { resolvePhobosConfig, effectiveMaxTics } from './config.js';

function b64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
  return out;
}

interface Bridge {
  pass(result: { trace: string }): void;
  error(err: { code: string; message?: string }): void;
}
interface GameContext {
  seed?: readonly number[] | null;
  config?: Record<string, unknown> | null;
  skin?: Record<string, string> | null;
  locale?: Record<string, string> | null;
}
interface Live {
  ccall(n: string, r: string | null, a: string[], v: number[]): number;
  HEAPU8: Uint8Array;
}

// Number of campaign arenas baked into the WAD (E1M1..E1M4). Bonus levels cycle
// through them; keep in sync with the CAMPAIGN list in engine/wad/build-phobos-wad.py.
const NUM_MAPS = 4;

function t(locale: Record<string, string> | null | undefined, key: string, fallback: string): string {
  return (locale && locale[key]) || fallback;
}

export function runPhobos({ container, bridge, ctx }: {
  container: HTMLElement; bridge: Bridge; ctx?: GameContext;
}): () => void {
  const locale = ctx?.locale ?? null;
  const skin = ctx?.skin ?? null;
  const cfg = resolvePhobosConfig((ctx?.config ?? null) as Record<string, unknown> | null);
  const { passKills, startLevel: startMap, waveCount } = cfg;
  const maxTics = effectiveMaxTics(cfg.timeLimit);
  const seed = (ctx?.seed && ctx.seed.length === 4 ? ctx.seed : [0xc0ffee01, 0xb0a75eed, 0x5eedface, 0x1d000d1e]) as readonly number[];

  const root = document.createElement('div');
  root.className = 'phobos';
  root.innerHTML = `
    <canvas class="phobos-canvas" width="${STAGE_WIDTH}" height="${STAGE_HEIGHT}"
            aria-label="${t(locale, 'ariaGame', 'Play DOOM and clear the demons to verify')}"></canvas>
    <div class="phobos-hud" aria-hidden="true">
      <span class="phobos-kills">0 / ${passKills}</span>
      <span class="phobos-badge" hidden>${t(locale, 'verifiedBadge', 'Verified')}</span>
    </div>
    <div class="phobos-start">
      <h2>${t(locale, 'startTitle', 'Phobos')}</h2>
      <p>${t(locale, 'startBody', `Clear ${passKills} demons to prove you're human.`)}</p>
      <button class="phobos-btn" type="button">${t(locale, 'startButton', 'Enter')}</button>
      <small>${t(locale, 'controlsHint', 'Arrows or WASD to move, Space or click to fire')}</small>
    </div>
    <div class="phobos-controls" aria-hidden="true">
      <button data-k="left" aria-label="${t(locale, 'ariaTurnLeft', 'Turn left')}">‹</button>
      <button data-k="fwd" aria-label="${t(locale, 'ariaForward', 'Forward')}">▲</button>
      <button data-k="right" aria-label="${t(locale, 'ariaTurnRight', 'Turn right')}">›</button>
      <button data-k="fire" aria-label="${t(locale, 'ariaFire', 'Fire')}">●</button>
    </div>
    <div class="phobos-cleared" hidden>
      <div class="phobos-cleared-mark" aria-hidden="true">✓</div>
      <h2 class="phobos-cleared-title"></h2>
      <p class="phobos-cleared-body"></p>
      <div class="phobos-cleared-actions">
        <button class="phobos-btn phobos-next" type="button">${t(locale, 'nextLevelButton', 'Next level')}</button>
        <button class="phobos-btn-ghost phobos-replay" type="button">${t(locale, 'replayButton', 'Replay')}</button>
      </div>
    </div>
    <div class="phobos-live" role="status" aria-live="polite"></div>`;
  container.appendChild(root);
  mountStyles(root, skin);

  const canvas = root.querySelector('canvas') as HTMLCanvasElement;
  const cctx = canvas.getContext('2d')!;
  const killsEl = root.querySelector('.phobos-kills') as HTMLElement;
  const badgeEl = root.querySelector('.phobos-badge') as HTMLElement;
  const startEl = root.querySelector('.phobos-start') as HTMLElement;
  const startBtn = root.querySelector('.phobos-btn') as HTMLButtonElement;
  const startBody = startEl.querySelector('p') as HTMLElement;
  const liveEl = root.querySelector('.phobos-live') as HTMLElement;
  const clearedEl = root.querySelector('.phobos-cleared') as HTMLElement;
  const clearedTitle = root.querySelector('.phobos-cleared-title') as HTMLElement;
  const clearedBody = root.querySelector('.phobos-cleared-body') as HTMLElement;

  let live: Live | null = null;
  let raf = 0;
  let running = false;
  let passed = false;
  let disposed = false;
  let image: ImageData | null = null;
  let level = 1;
  let wave = waveCount;
  let levelCleared = false;

  // The engine bundle is several MB and takes a moment to instantiate; gate the
  // Enter button behind a loading state so the round never starts before it is
  // ready (and the visitor sees progress instead of a frozen button).
  const startLabel = startBtn.textContent || 'Enter';
  startBtn.disabled = true;
  startBtn.textContent = t(locale, 'loading', 'Loading...');

  const sendKey = (pressed: number, key: number) =>
    live?.ccall('phobos_key', null, ['number', 'number'], [pressed, key]);

  const onKeyDown = (e: KeyboardEvent) => { const k = mapKey(e.code); if (k) { sendKey(1, k); e.preventDefault(); } };
  const onKeyUp = (e: KeyboardEvent) => { const k = mapKey(e.code); if (k) { sendKey(0, k); e.preventDefault(); } };

  function blit() {
    if (!live) return;
    const w = live.ccall('phobos_width', 'number', [], []);
    const h = live.ccall('phobos_height', 'number', [], []);
    const ptr = live.ccall('phobos_fb', 'number', [], []);
    if (!image || image.width !== w || image.height !== h) image = cctx.createImageData(w, h);
    const src = live.HEAPU8.subarray(ptr, ptr + w * h * 4);
    const dst = image.data;
    // DG_ScreenBuffer is uint32 ARGB (little-endian bytes B,G,R,A); canvas wants R,G,B,A.
    for (let i = 0; i < src.length; i += 4) {
      dst[i] = src[i + 2]!; dst[i + 1] = src[i + 1]!; dst[i + 2] = src[i]!; dst[i + 3] = 255;
    }
    if (canvas.width !== w) canvas.width = w;
    if (canvas.height !== h) canvas.height = h;
    cctx.putImageData(image, 0, 0);
  }

  function submitTrace() {
    const len = live!.ccall('phobos_tracelen', 'number', [], []);
    const ptr = live!.ccall('phobos_traceptr', 'number', [], []);
    const bytes = live!.HEAPU8.slice(ptr, ptr + len);
    let bin = '';
    for (let i = 0; i < bytes.length; i += 1) bin += String.fromCharCode(bytes[i]!);
    bridge.pass({ trace: btoa(bin) });
  }

  // End-of-round overlay. `cleared` = every demon down; otherwise the player
  // died. Either way the framing is a success if the captcha is already
  // verified; only an unverified death prompts a retry.
  function showEnd(cleared: boolean) {
    running = false;
    cancelAnimationFrame(raf);
    const nextBtn = root.querySelector('.phobos-next') as HTMLButtonElement;
    let title: string;
    let body: string;
    if (cleared) {
      title = t(locale, 'levelClearTitle', 'Level {level} cleared').replace('{level}', String(level));
      body = (passed ? `${t(locale, 'verifiedBadge', 'Verified')}. ` : '')
        + t(locale, 'levelClearBody', 'Demons cleared. Nice shooting.');
      nextBtn.hidden = false;
    } else if (passed) {
      // Died, but already verified: still a success.
      title = t(locale, 'verifiedBadge', 'Verified');
      body = t(locale, 'levelClearBody', 'Demons cleared. Nice shooting.');
      nextBtn.hidden = false;
    } else {
      // Died before verifying: retry only.
      title = t(locale, 'diedTitle', 'You died');
      body = t(locale, 'diedBody', 'Try again to verify.');
      nextBtn.hidden = true;
    }
    clearedTitle.textContent = title;
    clearedBody.textContent = body;
    clearedEl.hidden = false;
    liveEl.textContent = title;
    (nextBtn.hidden
      ? (root.querySelector('.phobos-replay') as HTMLButtonElement)
      : nextBtn).focus();
  }

  function checkProgress() {
    if (!live) return;
    const kills = live.ccall('phobos_killcount', 'number', [], []);
    killsEl.textContent = `${Math.min(kills, wave)} / ${wave}`;
    // Captcha gate: release on the server-owned pass threshold (the trace is
    // captured now, before any next-level reset overwrites it).
    if (!passed && kills >= passKills) {
      passed = true;
      submitTrace();
      badgeEl.hidden = false;
      liveEl.textContent = t(locale, 'announceVerified', 'Verified. You may keep playing.');
    }
    // Level cleared: every demon in this wave is down.
    if (!levelCleared && kills >= wave) {
      levelCleared = true;
      showEnd(true);
    }
  }

  function loop() {
    if (disposed || !running) return;
    live!.ccall('phobos_frame', null, [], []);
    blit();
    checkProgress();
    if (!running) return; // a level-clear this frame stopped the loop
    // Player death ends the round: success if already verified, else a retry.
    if (live!.ccall('phobos_player_dead', 'number', [], [])) {
      showEnd(false);
      return;
    }
    // Enforce the captcha tic budget so the recorded trace never exceeds what
    // the server replays (live == replay). Only the un-passed start level is
    // timed; once verified, bonus levels are untimed.
    if (!passed && live!.ccall('phobos_leveltime', 'number', [], []) >= maxTics) {
      running = false;
      startEl.hidden = false; // re-show the (localized) start screen to retry
      return;
    }
    raf = requestAnimationFrame(loop);
  }

  // Level 1 must run under the server-issued seed (it is the replayed captcha
  // round); bonus levels derive their own so each plays differently.
  function levelSeed(lvl: number): readonly number[] {
    if (lvl <= 1) return seed;
    const m = (lvl * 0x9e3779b9) >>> 0;
    return [(seed[0]! ^ m) >>> 0, (seed[1]! ^ (m * 3)) >>> 0,
      (seed[2]! ^ (m * 7)) >>> 0, (seed[3]! ^ (m * 13)) >>> 0];
  }

  function startLevel(lvl: number) {
    if (!live) return;
    level = lvl;
    wave = waveCount + (lvl - 1) * 2; // escalate the wave each level
    levelCleared = false;
    if (lvl === 1) { passed = false; badgeEl.hidden = true; }
    // Level 1 runs the configured captcha map (server replays it); bonus levels
    // cycle through the other arenas for variety. Level 1 honors the configured
    // respawn (must match the replay); bonus levels keep respawn off so the wave
    // stays finite and clearable.
    const map = lvl === 1 ? startMap : ((startMap - 1 + (lvl - 1)) % NUM_MAPS) + 1;
    const respawn = lvl === 1 ? (cfg.respawnMonsters ? 1 : 0) : 0;
    const s = levelSeed(lvl);
    live.ccall('phobos_start', null,
      ['number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number'],
      [s[0]! >>> 0, s[1]! >>> 0, s[2]! >>> 0, s[3]! >>> 0, map, wave,
        cfg.skill, cfg.fastMonsters ? 1 : 0, respawn]);
    startEl.hidden = true;
    clearedEl.hidden = true;
    (root.querySelector('.phobos-controls') as HTMLElement).removeAttribute('aria-hidden');
    killsEl.textContent = `0 / ${wave}`;
    running = true;
    liveEl.textContent = t(locale, 'announceStart', 'Go. Clear the demons.');
    canvas.focus();
    loop();
  }

  // Touch controls -> held DOOM keys.
  root.querySelectorAll<HTMLElement>('.phobos-controls button').forEach((btn) => {
    const k = { left: DOOM_KEYS.left, right: DOOM_KEYS.right, fwd: DOOM_KEYS.forward, fire: DOOM_KEYS.fire }[btn.dataset.k!]!;
    const down = (e: Event) => { e.preventDefault(); sendKey(1, k); };
    const up = (e: Event) => { e.preventDefault(); sendKey(0, k); };
    btn.addEventListener('touchstart', down, { passive: false });
    btn.addEventListener('touchend', up); btn.addEventListener('touchcancel', up);
    btn.addEventListener('mousedown', down); btn.addEventListener('mouseup', up);
  });
  canvas.addEventListener('mousedown', () => sendKey(1, DOOM_KEYS.fire));
  canvas.addEventListener('mouseup', () => sendKey(0, DOOM_KEYS.fire));
  canvas.tabIndex = 0;
  window.addEventListener('keydown', onKeyDown);
  window.addEventListener('keyup', onKeyUp);

  startBtn.addEventListener('click', () => startLevel(1));
  (root.querySelector('.phobos-next') as HTMLButtonElement)
    .addEventListener('click', () => startLevel(level + 1));
  (root.querySelector('.phobos-replay') as HTMLButtonElement)
    .addEventListener('click', () => startLevel(level));

  const wasmBytes = b64ToBytes(liveWasmB64);
  createPhobosLive({
    // Silence the DOOM engine's printf startup banner (Z_Init / W_Init / ...);
    // it would otherwise flood the host page's console.
    print: () => {},
    printErr: () => {},
    instantiateWasm(
      imports: WebAssembly.Imports,
      success: (inst: WebAssembly.Instance, mod: WebAssembly.Module) => void,
    ) {
      // Runtime instantiation from bytes is allowed in the live iframe.
      WebAssembly.instantiate(wasmBytes, imports).then((r) => {
        const src = r as unknown as WebAssembly.WebAssemblyInstantiatedSource;
        success(src.instance, src.module);
      });
      return {};
    },
  }).then((M: Live) => {
    if (disposed) return;
    live = M;
    blit(); // show the booted arena behind the start overlay
    startBtn.disabled = false; // engine ready: enable the round
    startBtn.textContent = startLabel;
  }).catch((e: unknown) => {
    startBtn.textContent = t(locale, 'loadError', 'Failed to load');
    bridge.error({ code: 'engine-load', message: e instanceof Error ? e.message : 'failed to load' });
  });

  return () => {
    disposed = true; running = false;
    cancelAnimationFrame(raf);
    window.removeEventListener('keydown', onKeyDown);
    window.removeEventListener('keyup', onKeyUp);
    root.remove();
  };
}
