// Ambient declarations for the generated Emscripten glue + the headless WASM
// module so `tsc` type-checks without the built artifacts present.
declare module '../build/phobos-headless.js' {
  interface PhobosFactoryOptions {
    instantiateWasm?(
      imports: WebAssembly.Imports,
      success: (inst: WebAssembly.Instance, mod: WebAssembly.Module) => void,
    ): WebAssembly.Exports | object;
  }
  const createPhobos: (opts?: PhobosFactoryOptions) => Promise<unknown>;
  export default createPhobos;
}

declare module './phobos.wasm' {
  const mod: WebAssembly.Module;
  export default mod;
}

declare module '../build/phobos-live.js' {
  interface PhobosLiveOptions {
    instantiateWasm?(
      imports: WebAssembly.Imports,
      success: (inst: WebAssembly.Instance, mod: WebAssembly.Module) => void,
    ): WebAssembly.Exports | object;
  }
  const createPhobosLive: (opts?: PhobosLiveOptions) => Promise<unknown>;
  export default createPhobosLive;
}

// Generated by build:engines (excluded from tsc; resolved by the bundler).
declare module './generated/phobos-live-wasm.js' {
  const wasmB64: string;
  export default wasmB64;
}
