// Ambient declarations for the generated Emscripten glue + the headless WASM
// module so `tsc` type-checks without the built artifacts present.
interface EmscriptenFactoryOptions {
  instantiateWasm?(
    imports: WebAssembly.Imports,
    success: (inst: WebAssembly.Instance, mod: WebAssembly.Module) => void,
  ): WebAssembly.Exports | object;
  print?(text: string): void;
  printErr?(text: string): void;
}

declare module '../build/phobos-headless.js' {
  const createPhobos: (opts?: EmscriptenFactoryOptions) => Promise<unknown>;
  export default createPhobos;
}

declare module './phobos.wasm' {
  const mod: WebAssembly.Module;
  export default mod;
}

declare module '../build/phobos-live.js' {
  const createPhobosLive: (opts?: EmscriptenFactoryOptions) => Promise<unknown>;
  export default createPhobosLive;
}

// Generated by build:engines (excluded from tsc; resolved by the bundler).
declare module './generated/phobos-live-wasm.js' {
  const wasmB64: string;
  export default wasmB64;
}
